### 첫번째 회원 등록
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "임상수",
  "email": "sangsoo@example.com"
}

### 두번째 회원 등록
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "홍길동",
  "email": "hong@example.com"
}

### 1번 회원 조회
GET http://localhost:8080/members/1

### 전체 회원 조회
GET http://localhost:8080/members

### 존재하지 않는 회원 조회
GET http://localhost:8080/members/999

### 회원 등록
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "임상수",
  "email": "sangsoo@example.com"
}

### 회원 수정
PUT http://localhost:8080/members/1
Content-Type: application/json

{
  "name": "수정된 임상수",
  "email": "updated@example.com"
}

### 수정된 회원 조회
GET http://localhost:8080/members/1

### 회원 삭제
DELETE http://localhost:8080/members/1

### 삭제된 회원 조회
GET http://localhost:8080/members/1

### 이름이 공백인 회원 등록
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "   ",
  "email": "sangsoo@example.com"
}

### 같은 이메일로 중복 회원 등록
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "다른 사람",
  "email": "sangsoo@example.com"
}


###
GET http://localhost:8080/beans/check

### 서블릿 GET 요청
GET http://localhost:8080/servlet/hello?name=임상수

### 서블릿 POST 요청
POST http://localhost:8080/servlet/hello
Content-Type: application/json

{
  "name": "임상수"
}

### 정상 회원 ID 변환
GET http://localhost:8080/conversion/members/member-10

### 단일 파일 업로드
POST http://localhost:8080/files
Content-Type: multipart/form-data; boundary=FileBoundary

--FileBoundary
Content-Disposition: form-data; name="file"; filename="sample.txt"
Content-Type: text/plain

< ./sample.txt
--FileBoundary--

### JSON과 파일 함께 업로드
POST http://localhost:8080/files/with-data
Content-Type: multipart/form-data; boundary=UploadBoundary

--UploadBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "title": "Spring 파일 업로드",
  "description": "JSON과 파일을 함께 전송합니다."
}
--UploadBoundary
Content-Disposition: form-data; name="file"; filename="sample.txt"
Content-Type: text/plain

< ./sample.txt
--UploadBoundary--